version: '2'

services:
  desktop:
    build: .
    volumes:
      - ./scripts/start:/usr/local/bin/start
      - ./app:/data
    environment:
      FULCRUM_ORG: $FULCRUM_ORG
      FULCRUM_TOKEN: $FULCRUM_TOKEN
      FULCRUM_PG_HOST: $PG_HOST
      FULCRUM_PG_PORT: $PG_PORT
      FULCRUM_PG_USER: $PG_USER
      FULCRUM_PG_PASSWORD: $PG_PASSWORD
      FULCRUM_PG_DATABASE: $PG_DATABASE
      FULCRUM_GPKG_ENABLED: $GPKG_ENABLED
      FULCRUM_MEDIA_ENABLED: $MEDIA_ENABLED
      FULCRUM_REPORTS_ENABLED: $REPORTS_ENABLED
      FULCRUM_PG_ENABLED: $PG_ENABLED
      FULCRUM_SYNC_ARGS: $SYNC_ARGS
      FULCRUM_REPORTS_ARGS: $REPORTS_ARGS
      FULCRUM_GPKG_ARGS: $GPKG_ARGS
      FULCRUM_PG_ARGS: $PG_ARGS
