#!/bin/bash

docker run \
  -e FULCRUM_ORG \
  -e FULCRUM_TOKEN \
  -e FULCRUM_GPKG_ENABLED \
  -e FULCRUM_REPORTS_ENABLED \
  -e FULCRUM_SYNC_ARGS \
  -e FULCRUM_REPORTS_ARGS \
  -e FULCRUM_GPKG_ARGS \
  -e FULCRUM_PG_ARGS \
  -e FULCRUM_PG_ENABLED \
  -e FULCRUM_PG_HOST \
  -e FULCRUM_PG_PORT \
  -e FULCRUM_PG_DATABASE \
  -e FULCRUM_PG_USER \
  -e FULCRUM_PG_PASSWORD \
  -e FULCRUM_PG_ARGS \
  --rm \
  -v $(pwd)/app:/data \
  -it fulcrumapp/sync $@
