#!/bin/bash

#set -e

export FULCRUM_DATA_PATH=/data/db
export FULCRUM_MEDIA_PATH=/data
export FULCRUM_REPORTS_PATH=/data/reports
export FULCRUM_GPKG_PATH=/data/geopackage

error () {
  echo $1
  exit 1
}

if [ -z "$FULCRUM_ORG" ]; then
  error "FULCRUM_ORG must specify the organization name"
fi

if [ -z "$FULCRUM_TOKEN" ]; then
  error "FULCRUM_TOKEN must specify the API token"
fi

export REPORTS_ENABLED=${REPORTS_ENABLED:=no}
export REPORTS_ARGS=${REPORTS_ARGS:="--file-name id"}

export MEDIA_ENABLED=${MEDIA_ENABLED:=no}

export GPKG_ENABLED=${GPKG_ENABLED:=no}
export GPKG_NAME=${GPKG_NAME:="$FULCRUM_ORG"}
export GPKG_ARGS=${GPKG_ARGS:="--gpkg-underscore-names --gpkg-drop false --no-gpkg-user-info --no-gpkg-joined-names"}

export PG_ENABLED=${PG_ENABLED:=no}
export PG_ARGS=${PG_ARGS:="--pg-underscore-names"}

# assign the psql-specific variables
export PGHOST=${PGHOST:=$FULCRUM_PG_HOST}
export PGPORT=${PGPORT:=$FULCRUM_PG_PORT}
export PGDATABASE=${PGDATABASE:=$FULCRUM_PG_DATABASE}
export PGUSER=${PGUSER:=$FULCRUM_PG_USER}
export PGPASSWORD=${PGPASSWORD:=$FULCRUM_PG_PASSWORD}

export PLUGIN_PATH=/root/.fulcrum/plugins
export PLUGIN_PATH_ALL=/root/.fulcrum/plugins-all

mkdir -p $PLUGIN_PATH_DISABLED

disable_plugin () {
  rm -f $PLUGIN_PATH/fulcrum-desktop-$1
}

enable_plugin () {
  ln -s $PLUGIN_PATH_ALL/fulcrum-desktop-$1 $PLUGIN_PATH/fulcrum-desktop-$1
}

disable_plugin 'postgres'
disable_plugin 'media'
disable_plugin 'reports'
disable_plugin 'geopackage'

if [[ $PG_ENABLED != "no" ]]; then
  echo "Connecting to psql $PGHOST:$PGPORT@$PGDATABASE as $PGUSER"

  /usr/local/bin/wait-for-postgres

  psql -d postgres -c "CREATE DATABASE $PGDATABASE;"

  psql -d $PGDATABASE -c 'CREATE EXTENSION IF NOT EXISTS postgis;'

  enable_plugin 'postgres'
fi

if [[ $MEDIA_ENABLED != "no" ]]; then
  enable_plugin 'media'
fi

if [[ $REPORTS_ENABLED != "no" ]]; then
  enable_plugin 'reports'
fi

if [[ $GPKG_ENABLED != "no" ]]; then
  enable_plugin 'geopackage'
fi

mkdir -p $FULCRUM_DATA_PATH

fulcrum setup

fulcrum sync --simple-output $PG_ARGS $SYNC_ARGS

if [[ $MEDIA_ENABLED != "no" ]]; then
  echo "Processing media..."
  fulcrum media
fi

if [[ $REPORTS_ENABLED != "no" ]]; then
  echo "Processing reports..."
  mkdir -p /data/templates

  if [ -f /data/templates/template.ejs ]; then
    export FULCRUM_REPORTS_TEMPLATE="/data/templates/template.ejs"
  fi

  if [ -f /data/templates/header.ejs ]; then
    export FULCRUM_REPORTS_HEADER="/data/templates/header.ejs"
  fi

  if [ -f /data/templates/footer.ejs ]; then
    export FULCRUM_REPORTS_FOOTER="/data/templates/footer.ejs"
  fi

  fulcrum reports $REPORTS_ARGS
fi

if [[ $GPKG_ENABLED != "no" ]]; then
  echo "Processing geopackage..."

  mkdir -p /data/geopackage

  fulcrum geopackage $GPKG_ARGS

  ogr2ogr -f CSV -overwrite "/data/csv" "/data/geopackage/$GPKG_NAME.gpkg" -lco GEOMETRY=AS_XY
fi
